Repository axmolengine/axmol, pull requests merged in 2020-02, with the labels that each got.

#35 add windows android start guide
  README.md
Labels: documentation

#39 Refactor UserDefault, add plain mode for win32.
  cocos/base/CCUserDefault.cpp
Labels: enhancement

#40 Refactor UserDefault, cbc128 encrypt support.
  cocos/base/CCUserDefault.cpp
  cocos/base/CCUserDefault.h
Labels: enhancement

#44 Fix travis ci ios build issue
  README.md
  cmake/ios.toolchain.cmake
  tools/travis-scripts/run-script.sh
Labels: enhancement

#47 Update README.md
  README.md
Labels: documentation

#50 add astc support (Great Job)
  cocos/base/CCConfiguration.cpp
  cocos/base/CCConfiguration.h
  cocos/base/CMakeLists.txt
  cocos/base/astc.cpp
  cocos/base/astc.h
  cocos/platform/CCImage.cpp
  cocos/platform/CCImage.h
  cocos/renderer/CCTexture2D.cpp
  cocos/renderer/backend/Texture.cpp
  cocos/renderer/backend/Types.h
  cocos/renderer/backend/opengl/DeviceInfoGL.cpp
  cocos/renderer/backend/opengl/UtilsGL.cpp
  external/config.json
  tests/cpp-tests/Classes/SpriteTest/SpriteTest.cpp
  tests/cpp-tests/Classes/SpriteTest/SpriteTest.h
  tests/cpp-tests/Resources/Images/ASTC_RGB.astc
  tests/cpp-tests/Resources/Images/ASTC_RGBA.astc
  tests/cpp-tests/Resources/Images/ASTC_RGBA_8x8.astc
Labels: enhancement

#52 fix #51
  cocos/2d/CCLayer.cpp
  cocos/editor-support/cocostudio/ActionTimeline/CCBoneNode.cpp
  cocos/editor-support/cocostudio/ActionTimeline/CCSkeletonNode.cpp
  cocos/renderer/backend/ProgramCache.cpp
  cocos/renderer/backend/Types.h
  cocos/renderer/backend/opengl/ProgramGL.cpp
Labels: bug

#57 Update deps to v29
  cocos/base/CCUserDefault.cpp
  external/config.json
Labels: enhancement

#56 Make astc works on ios platform.
  cocos/renderer/CCTexture2D.cpp
  cocos/renderer/backend/metal/TextureMTL.mm
  cocos/renderer/backend/metal/Utils.mm
Labels: enhancement

#58 Make multi-meta-textures feature works on Apple Metal.
  cocos/renderer/backend/Texture.cpp
  cocos/renderer/backend/Texture.h
  cocos/renderer/backend/metal/CommandBufferMTL.mm
  cocos/renderer/backend/metal/TextureMTL.h
  cocos/renderer/backend/metal/TextureMTL.mm
  cocos/renderer/backend/opengl/CommandBufferGL.cpp
  cocos/renderer/backend/opengl/TextureGL.cpp
  cocos/renderer/backend/opengl/TextureGL.h
Labels: enhancement

#60 Remove xxtea, cleanup xxtea reference sources
  cocos/scripting/lua-bindings/manual/CCLuaStack.cpp
  cocos/scripting/lua-bindings/manual/CCLuaStack.h
  tests/lua-tests/project/Classes/AppDelegate.cpp
Labels: enhancement

#62 Use modern gl/gles loader 'glad' to instead 'glew'
  cmake/Modules/CocosConfigDefine.cmake
  cocos/platform/desktop/CCGLViewImpl-desktop.cpp
  cocos/platform/desktop/CCGLViewImpl-desktop.h
  cocos/platform/win32/CCGL-win32.h
  external/config.json
Labels: enhancement

#63 Sync glad
  cocos/platform/desktop/CCGLViewImpl-desktop.cpp
  external/config.json
Labels: enhancement

#66 Remove duplicated code
  cocos/renderer/backend/opengl/TextureGL.cpp
Labels: enhancement

#69 fix #41
  README.md
  cocos/base/CCEnumClass.h
  cocos/base/bitmask.h
  cocos/base/ccTypes.h
  cocos/renderer/CCRenderer.cpp
  cocos/renderer/backend/Types.h
  cocos/renderer/backend/opengl/RenderPipelineGL.cpp
  external/config.json
Labels: bug

#71 Sync v3 pr-19256
  cocos/platform/android/java/src/org/cocos2dx/lib/Cocos2dxActivity.java
  cocos/platform/android/java/src/org/cocos2dx/lib/Cocos2dxGLSurfaceView.java
Labels: enhancement

#72 Sync v3 pr20107 & fix builtin shaders
  cocos/renderer/backend/opengl/ProgramGL.cpp
  cocos/renderer/shaders/positionTexture.frag
  cocos/renderer/shaders/positionTextureColor.frag
  cocos/renderer/shaders/positionTextureUColor.frag
Labels: enhancement

#76 Use original c lib minizip-1.2.0
  cocos/base/ZipUtils.h
  external/config.json
Labels: enhancement
