Repository axmolengine/axmol, pull requests merged in 2020-08, with the labels that each got.

#134 Refactor full screen support
  cocos/platform/desktop/CCGLViewImpl-desktop.cpp
  cocos/platform/desktop/CCGLViewImpl-desktop.h
  tests/cpp-tests/Classes/WindowTest/WindowTest.cpp
  tests/cpp-tests/Classes/WindowTest/WindowTest.h
Labels: bug, enhancement

#135 Unify plist implementation, remove apple specific sources.
  cocos/platform/CCFileUtils.cpp
  cocos/platform/apple/CCFileUtils-apple.h
  cocos/platform/apple/CCFileUtils-apple.mm
Labels: enhancement

#136 The switch to the third monitor was not working
  tests/cpp-tests/Classes/WindowTest/WindowTest.cpp
Labels: bug

#142 Finish dragonbones, all extensions can be remove one by one
  extensions/CMakeLists.txt
  extensions/cocostudio/ActionTimeline/CSLoader.cpp
  extensions/cocostudio/SpineSkeletonDataCache.cpp
  extensions/cocostudio/SpineSkeletonDataCache.h
  extensions/cocostudio/WidgetReader/ArmatureNodeReader/ArmatureNodeReader.cpp
  extensions/cocostudio/WidgetReader/SpineSkeletonReader/SpineSkeletonReader.cpp
  extensions/cocostudio/WidgetReader/SpineSkeletonReader/SpineSkeletonReader.h
  extensions/dragonbones/CCArmatureDisplay.cpp
  extensions/dragonbones/CCArmatureDisplay.h
  extensions/dragonbones/CCFactory.cpp
  extensions/dragonbones/CCFactory.h
  extensions/dragonbones/CCSlot.cpp
  extensions/dragonbones/CCSlot.h
  extensions/dragonbones/CCTextureAtlasData.h
  extensions/dragonbones/CMakeLists.txt
  extensions/dragonbones/parser/JSONDataParser.h
Labels: enhancement

#158 Simplify audio source again, merge audio sources
  cocos/CMakeLists.txt
  cocos/audio/AudioCache.cpp
  cocos/audio/AudioPlayer.cpp
  cocos/audio/CMakeLists.txt
  cocos/audio/apple/AudioEngineImpl.mm
  cocos/audio/include/AudioDecoderEXT.h
  cocos/audio/include/AudioEngineImpl.h
  cocos/audio/include/AudioPlayer.h
  cocos/audio/include/alconfig.h
  cocos/audio/src/AudioCache.cpp
  cocos/audio/src/AudioDecoder.cpp
  cocos/audio/src/AudioDecoderEXT.mm
  cocos/audio/src/AudioDecoderManager.cpp
  cocos/audio/src/AudioDecoderMp3.cpp
  cocos/audio/src/AudioDecoderOgg.cpp
  cocos/audio/src/AudioDecoderWav.cpp
  cocos/audio/src/AudioEngine.cpp
  cocos/audio/src/AudioEngineImpl.cpp
  cocos/audio/src/AudioEngineImpl.mm
  cocos/audio/src/AudioPlayer.cpp
Labels: enhancement

#160 fix-157
  cocos/audio/CMakeLists.txt
  cocos/audio/include/alconfig.h
  cocos/audio/src/AudioEngineImpl.cpp
  cocos/audio/src/AudioEngineImpl.mm
  cocos/audio/src/alink.cpp
Labels: enhancement

#162 Use CC0-1.0 licensed decoder 'minimp3' to replace LGPL licensed decod…
  cocos/audio/CMakeLists.txt
  cocos/audio/include/AudioDecoderMp3.h
  cocos/audio/src/AudioDecoderManager.cpp
  cocos/audio/src/AudioDecoderMp3.cpp
  cocos/audio/src/android-link.cpp
  external/config.json
Labels: enhancement

#163 Improve shared library for android, update android devtools
  README.md
  README_CN.md
  cmake/Modules/CocosConfigDepend.cmake
  cocos/CMakeLists.txt
  external/config.json
  templates/cpp-template-default/CMakeLists.txt
  templates/cpp-template-default/proj.android/app/src/org/cocos2dx/cpp/AppActivity.java
  templates/cpp-template-default/proj.android/build.gradle
  templates/cpp-template-default/proj.android/gradle/wrapper/gradle-wrapper.properties
  templates/lua-template-default/CMakeLists.txt
  templates/lua-template-default/frameworks/runtime-src/proj.android/app/src/org/cocos2dx/lua/AppActivity.java
  templates/lua-template-default/frameworks/runtime-src/proj.android/build.gradle
  templates/lua-template-default/frameworks/runtime-src/proj.android/gradle/wrapper/gradle-wrapper.properties
  tests/cpp-empty-test/CMakeLists.txt
  tests/cpp-empty-test/proj.android/app/src/org/cocos2dx/cpp_empty_test/AppActivity.java
  tests/cpp-empty-test/proj.android/build.gradle
  tests/cpp-empty-test/proj.android/gradle/wrapper/gradle-wrapper.properties
  tests/cpp-tests/CMakeLists.txt
  tests/cpp-tests/proj.android/app/src/org/cocos2dx/cpp_tests/AppActivity.java
  tests/cpp-tests/proj.android/build.gradle
  tests/cpp-tests/proj.android/gradle.properties
  tests/cpp-tests/proj.android/gradle/wrapper/gradle-wrapper.properties
  tests/fairygui-tests/CMakeLists.txt
  tests/fairygui-tests/proj.android/app/src/org/cocos2dx/fairygui_tests/AppActivity.java
  tests/fairygui-tests/proj.android/build.gradle
  tests/fairygui-tests/proj.android/gradle/wrapper/gradle-wrapper.properties
  tests/lua-empty-test/project/CMakeLists.txt
  tests/lua-empty-test/project/proj.android/app/src/org/cocos2dx/lua_empty_test/AppActivity.java
  tests/lua-empty-test/project/proj.android/build.gradle
  tests/lua-empty-test/project/proj.android/gradle/wrapper/gradle-wrapper.properties
  tests/lua-tests/project/CMakeLists.txt
  tests/lua-tests/project/proj.android/app/src/org/cocos2dx/lua_tests/AppActivity.java
  tests/lua-tests/project/proj.android/build.gradle
  tests/lua-tests/project/proj.android/gradle/wrapper/gradle-wrapper.properties
  tests/performance-tests/proj.android/app/src/org/cocos2dx/cpp/AppActivity.java
  tests/performance-tests/proj.android/build.gradle
  tests/performance-tests/proj.android/gradle/wrapper/gradle-wrapper.properties
  tools/travis-scripts/run-script.sh
Labels: enhancement

#167 Fix label crashing
  cocos/2d/CCLabel.cpp
  cocos/2d/CCLabel.h
  cocos/renderer/CCCustomCommand.cpp
  cocos/renderer/CCCustomCommand.h
Labels: bug

#172 Add API 'utils::killCurrentProcess' to kill game immidiately
  cocos/base/ccUtils.cpp
  cocos/base/ccUtils.h
Labels: enhancement

#174 Rename PXFileStream to CCFileStream
  cocos/audio/include/AudioDecoder.h
  cocos/audio/include/AudioDecoderMp3.h
  cocos/audio/include/AudioDecoderOgg.h
  cocos/audio/include/AudioDecoderWav.h
  cocos/audio/src/AudioDecoderMp3.cpp
  cocos/audio/src/AudioDecoderOgg.cpp
  cocos/audio/src/AudioDecoderWav.cpp
  cocos/network/CCDownloader-curl.cpp
  cocos/platform/CCFileStream.cpp
  cocos/platform/CCFileStream.h
  cocos/platform/CMakeLists.txt
Labels: enhancement

#175 Freetype stream parsing
  cocos/2d/CCFontFreeType.cpp
  cocos/2d/CCFontFreeType.h
  cocos/platform/CCFileStream.cpp
  cocos/platform/CCFileStream.h
Labels: enhancement

#182 Only leave one TMXLayer & TMXTileMap
  cocos/2d/CCFastTMXLayer.cpp
  cocos/2d/CCFastTMXLayer.h
  cocos/2d/CCFastTMXTiledMap.cpp
  cocos/2d/CCFastTMXTiledMap.h
  cocos/2d/CCTMXLayer.cpp
  cocos/2d/CCTMXLayer.h
  cocos/2d/CCTMXTiledMap.cpp
  cocos/2d/CCTMXTiledMap.h
  cocos/2d/CCTMXXMLParser.cpp
  cocos/2d/CCTMXXMLParser.h
  cocos/2d/CMakeLists.txt
  cocos/cocos2d.h
  cocos/scripting/deprecated/CCDeprecated.h
  cocos/scripting/lua-bindings/auto/lua_cocos2dx_auto.cpp
  cocos/scripting/lua-bindings/manual/cocos2d/lua_cocos2dx_manual.cpp
  extensions/cocostudio/ActionTimeline/CSLoader.cpp
  extensions/cocostudio/CCComRender.cpp
  extensions/cocostudio/WidgetReader/GameMapReader/GameMapReader.cpp
  tests/cpp-tests/CMakeLists.txt
  tests/cpp-tests/Classes/TileMapTest/TileMapTest.cpp
  tests/cpp-tests/Classes/TileMapTest/TileMapTest.h
  tests/cpp-tests/Classes/TileMapTest/TileMapTest2.cpp
  tests/cpp-tests/Classes/TileMapTest/TileMapTest2.h
  tests/cpp-tests/Classes/controller.cpp
  tests/cpp-tests/Classes/tests.h
  tests/cpp-tests/Resources/TileMaps/tile_animation_test.tmx
Labels: enhancement

#184 fix multi-texture2d support
  cocos/renderer/backend/ProgramState.cpp
  cocos/renderer/backend/ProgramState.h
  cocos/renderer/backend/metal/CommandBufferMTL.mm
  cocos/renderer/backend/opengl/CommandBufferGL.cpp
  cocos/renderer/backend/opengl/TextureGL.cpp
  cocos/renderer/backend/opengl/TextureGL.h
Labels: bug

#186 Fix ASTC bytesPerRow calculation
  cocos/renderer/backend/metal/TextureMTL.mm
Labels: bug
