Repository axmolengine/axmol, pull requests merged in 2020-11, with the labels that each got.

#256 [Metal] matching depth stencil state
  cocos/renderer/CCRenderer.cpp
  cocos/renderer/backend/DepthStencilState.cpp
  cocos/renderer/backend/DepthStencilState.h
  cocos/renderer/backend/metal/CommandBufferMTL.h
  cocos/renderer/backend/metal/CommandBufferMTL.mm
  cocos/renderer/backend/metal/RenderPipelineMTL.h
  cocos/renderer/backend/metal/RenderPipelineMTL.mm
  cocos/renderer/backend/metal/RenderTargetMTL.mm
Labels: enhancement

#259 Fix crash when enable encrypt for UserDefault
  cocos/base/CCUserDefault.cpp
Labels: bug

#265 Update README.md
  README.md
Labels: documentation

#266 Update README.md
  external/README.md
Labels: documentation

#268 Fix manifest version greater check
  extensions/assets-manager/Manifest.cpp
Labels: bug, official-v4

#273 Add "Box2d - Basic" test
  tests/cpp-tests/CMakeLists.txt
  tests/cpp-tests/Classes/Box2DTest/Box2dTest.cpp
  tests/cpp-tests/Classes/Box2DTest/Box2dTest.h
  tests/cpp-tests/Classes/controller.cpp
  tests/cpp-tests/Classes/tests.h
Labels: enhancement

#283 Allow user to set custom program type value
  cocos/renderer/backend/Program.h
Labels: enhancement

#285 Fix ListView dimensions when child elements are scaled
  cocos/ui/UIListView.cpp
Labels: enhancement
