Repository axmolengine/axmol, pull requests merged in 2021-08, with the labels that each got.

#284 Support custom texture atlas formats
  cocos/2d/CCPlistSpriteSheetLoader.cpp
  cocos/2d/CCPlistSpriteSheetLoader.h
  cocos/2d/CCSpriteFrameCache.cpp
  cocos/2d/CCSpriteFrameCache.h
  cocos/2d/CCSpriteSheetLoader.cpp
  cocos/2d/CCSpriteSheetLoader.h
  cocos/2d/CMakeLists.txt
  tests/cpp-tests/Classes/SpriteFrameCacheTest/SpriteFrameCacheTest.cpp
  tests/cpp-tests/Classes/SpriteFrameCacheTest/SpriteFrameCacheTest.h
  tests/cpp-tests/Classes/SpriteTest/SpriteTest.cpp
  tests/cpp-tests/Resources/Images/sprite_frames_test/test_RGB8888_generic.json
  tests/cpp-tests/Resources/Images/sprite_frames_test/test_RGB8888_generic.png
Labels: enhancement

#459 Update sprite sheet API to allow custom sprite sheet texture filename to be used
  cocos/2d/CCPlistSpriteSheetLoader.cpp
  cocos/2d/CCPlistSpriteSheetLoader.h
  cocos/2d/CCSpriteFrameCache.cpp
  cocos/2d/CCSpriteFrameCache.h
  cocos/2d/CCSpriteSheetLoader.h
  tests/cpp-tests/Classes/BaseTest.cpp
  tests/cpp-tests/Classes/SpriteFrameCacheTest/SpriteFrameCacheTest.cpp
Labels: bug, enhancement

#469 Update FileStream seek, tell and size to support files greater than 4GB files
  cocos/platform/CCFileStream.h
  cocos/platform/CCPosixFileStream.cpp
  cocos/platform/CCPosixFileStream.h
Labels: enhancement

#481 Fix crash problem when load a non-truetype .ttf file
  cocos/2d/CCFontFreeType.cpp
  cocos/2d/CCFontFreeType.h
Labels: bug

#485 Fix spine command pipeline state uniform location mismatch
  extensions/spine/SkeletonBatch.cpp
  extensions/spine/SkeletonBatch.h
Labels: bug, spine-runtime
