Repository axmolengine/axmol, pull requests merged in 2022-10, with the labels that each got.

#890 Check cpp20 complings for all platforms
  thirdparty/pugixml/pugixml.hpp
Labels: cpp20

#905 Improve AutoPolygon::generateTriangles performance
  core/2d/CCAutoPolygon.cpp
Labels: enhancement

#901 precompile_headers all platforms
  core/CMakeLists.txt
  core/precheader.cpp
  core/precheader.h
  tests/cpp-tests/CMakeLists.txt
  tests/cpp-tests/Classes/precheader.cpp
  tests/cpp-tests/Classes/precheader.h
Labels: enhancement

#916 Improve code quality (step1. Oct)
  .github/workflows/pr-ci.yml
  core/2d/CCMotionStreak.cpp
  core/2d/CCSpriteFrameCache.cpp
  core/2d/CCSpriteFrameCache.h
  core/3d/CCAnimation3D.cpp
  core/3d/CCMesh.cpp
  core/3d/CCTerrain.cpp
  core/CMakeLists.txt
  core/axmol.natvis
  core/base/CCEventDispatcher.cpp
  core/base/CCProperties.cpp
  core/base/CCProperties.h
  core/base/ZipUtils.cpp
  core/base/axstd.h
  core/base/pod_vector.h
  core/physics/CCPhysicsWorld.cpp
  core/platform/CCGLView.cpp
  core/platform/CCImage.cpp
  core/renderer/CCMaterial.cpp
  core/renderer/CCMaterial.h
  core/renderer/CCRenderer.cpp
  core/renderer/backend/opengl/ProgramGL.cpp
  core/renderer/backend/opengl/ShaderModuleGL.cpp
  tests/cpp-tests/Classes/MaterialSystemTest/MaterialSystemTest.cpp
  tools/win-ci/build.ps1
Labels: enhancement, pinned

#927 Fix downloader crash in the lua coroutine
  extensions/scripting/lua-bindings/manual/network/lua_downloader.cpp
Labels: bug

#942 Remove FileUtils::searchResolutionsOrderArray
  core/base/CCConsole.cpp
  core/platform/CCFileUtils.cpp
  core/platform/CCFileUtils.h
  core/platform/apple/CCFileUtils-apple.h
  core/platform/apple/CCFileUtils-apple.mm
  core/platform/win32/CCFileUtils-win32.cpp
  core/platform/win32/CCFileUtils-win32.h
  extensions/Effekseer/CMakeLists.txt
  extensions/scripting/lua-bindings/auto/axlua_base_auto.cpp
  tests/cpp-tests/Classes/FileUtilsTest/FileUtilsTest.cpp
  tests/cpp-tests/Classes/FileUtilsTest/FileUtilsTest.h
Labels: enhancement
