Repository axmolengine/axmol, pull requests merged in 2022-08, with the labels that each got.

#772 Replace getSpriteFrameByName() with findFrame() in cocos-studio
  extensions/cocostudio/ActionTimeline/CCActionTimelineCache.cpp
  extensions/cocostudio/ActionTimeline/CCFrame.cpp
  extensions/cocostudio/ActionTimeline/CSLoader.cpp
  extensions/cocostudio/CCSkin.cpp
  extensions/cocostudio/CCSpriteFrameCacheHelper.cpp
  extensions/cocostudio/WidgetReader/ButtonReader/ButtonReader.cpp
  extensions/cocostudio/WidgetReader/CheckBoxReader/CheckBoxReader.cpp
  extensions/cocostudio/WidgetReader/ImageViewReader/ImageViewReader.cpp
  extensions/cocostudio/WidgetReader/LayoutReader/LayoutReader.cpp
  extensions/cocostudio/WidgetReader/ListViewReader/ListViewReader.cpp
  extensions/cocostudio/WidgetReader/LoadingBarReader/LoadingBarReader.cpp
  extensions/cocostudio/WidgetReader/PageViewReader/PageViewReader.cpp
  extensions/cocostudio/WidgetReader/RadioButtonReader/RadioButtonReader.cpp
  extensions/cocostudio/WidgetReader/ScrollViewReader/ScrollViewReader.cpp
  extensions/cocostudio/WidgetReader/SliderReader/SliderReader.cpp
  extensions/cocostudio/WidgetReader/SpriteReader/SpriteReader.cpp
  extensions/cocostudio/WidgetReader/TabControlReader/TabControlReader.cpp
Labels: enhancement

#774 robin_const_iterator Bug fix in robin_hash.h
  thirdparty/robin-map/include/tsl/robin_hash.h
Labels: bug

#778 [PROPOSAL] Add wireframe rendering and function classification improvements.
  core/3d/CCMesh.cpp
  core/3d/CCMesh.h
  core/3d/CCMeshRenderer.cpp
  core/3d/CCMeshRenderer.h
  core/renderer/CCMaterial.cpp
  core/renderer/CCMaterial.h
  core/renderer/CCRenderCommand.h
  core/renderer/CCRenderer.cpp
  core/renderer/backend/CommandBuffer.h
  core/renderer/backend/metal/CommandBufferMTL.h
  core/renderer/backend/metal/CommandBufferMTL.mm
  core/renderer/backend/opengl/CommandBufferGL.cpp
  core/renderer/backend/opengl/CommandBufferGL.h
  extensions/scripting/lua-bindings/auto/lua_axis_3d_auto.cpp
  tests/cpp-tests/Classes/MeshRendererTest/MeshRendererTest.cpp
Labels: enhancement

#785 replace push_back() vs emplace_back() on extension
  extensions/GUI/CCControlExtension/CCControl.cpp
  extensions/GUI/CCScrollView/CCScrollView.cpp
  extensions/Live2D/Framework/src/CubismFramework.cpp
  extensions/Particle3D/CCParticle3DRender.cpp
  extensions/Particle3D/CCParticleSystem3D.cpp
  extensions/Particle3D/CCParticleSystem3D.h
  extensions/Particle3D/PU/CCPUAffector.cpp
  extensions/Particle3D/PU/CCPUBeamRender.cpp
  extensions/Particle3D/PU/CCPUDynamicAttribute.cpp
  extensions/Particle3D/PU/CCPUMaterialManager.cpp
  extensions/Particle3D/PU/CCPUMeshSurfaceEmitter.cpp
  extensions/Particle3D/PU/CCPUObserver.cpp
  extensions/Particle3D/PU/CCPUParticleSystem3D.cpp
  extensions/Particle3D/PU/CCPUParticleSystem3DTranslator.cpp
  extensions/Particle3D/PU/CCPUPositionEmitter.cpp
  extensions/Particle3D/PU/CCPURender.cpp
  extensions/Particle3D/PU/CCPURibbonTrail.cpp
  extensions/Particle3D/PU/CCPURibbonTrailRender.cpp
  extensions/Particle3D/PU/CCPUScriptCompiler.cpp
  extensions/Particle3D/PU/CCPUScriptLexer.cpp
  extensions/Particle3D/PU/CCPUScriptParser.cpp
  extensions/Particle3D/PU/CCPUSimpleSpline.cpp
  extensions/assets-manager/AssetsManagerEx.cpp
  extensions/assets-manager/Manifest.cpp
  extensions/cocostudio/ActionTimeline/CCActionTimelineCache.cpp
  extensions/cocostudio/ActionTimeline/CSLoader.cpp
  extensions/cocostudio/CCActionFrame.cpp
  extensions/cocostudio/CCActionNode.cpp
  extensions/cocostudio/CCArmatureAnimation.cpp
  extensions/cocostudio/CCArmatureDataManager.cpp
  extensions/cocostudio/CCColliderDetector.cpp
  extensions/cocostudio/CCDataReaderHelper.cpp
  extensions/cocostudio/CCDatas.cpp
  extensions/cocostudio/CCSSceneReader.cpp
  extensions/cocostudio/CCSpriteFrameCacheHelper.cpp
  extensions/cocostudio/FlatBuffersSerialize.cpp
  extensions/cocostudio/WidgetReader/ButtonReader/ButtonReader.cpp
  extensions/cocostudio/WidgetReader/CheckBoxReader/CheckBoxReader.cpp
  extensions/cocostudio/WidgetReader/GameNode3DReader/GameNode3DReader.cpp
  extensions/cocostudio/WidgetReader/ImageViewReader/ImageViewReader.cpp
  extensions/cocostudio/WidgetReader/LayoutReader/LayoutReader.cpp
  extensions/cocostudio/WidgetReader/ListViewReader/ListViewReader.cpp
  extensions/cocostudio/WidgetReader/LoadingBarReader/LoadingBarReader.cpp
  extensions/cocostudio/WidgetReader/PageViewReader/PageViewReader.cpp
  extensions/cocostudio/WidgetReader/RadioButtonReader/RadioButtonReader.cpp
  extensions/cocostudio/WidgetReader/ScrollViewReader/ScrollViewReader.cpp
  extensions/cocostudio/WidgetReader/SliderReader/SliderReader.cpp
  extensions/cocostudio/WidgetReader/SpineSkeletonReader/SpineSkeletonReader.cpp
  extensions/cocostudio/WidgetReader/SpriteReader/SpriteReader.cpp
  extensions/cocostudio/WidgetReader/TabControlReader/TabControlReader.cpp
  extensions/cocostudio/WidgetReader/UserCameraReader/UserCameraReader.cpp
  extensions/scripting/lua-bindings/manual/LuaBasicConversions.cpp
  extensions/scripting/lua-bindings/manual/base/LuaScriptHandlerMgr.cpp
  extensions/scripting/lua-bindings/manual/network/lua_xml_http_request.cpp
  extensions/scripting/lua-bindings/manual/physics3d/axlua_physics3d_manual.cpp
  extensions/scripting/lua-bindings/manual/platform/android/CCLuaJavaBridge.cpp
Labels: enhancement

#792 [BUG] Fix camera view calculation and tidy up system.
  core/2d/CCCamera.cpp
  core/2d/CCCamera.h
  core/2d/CCScene.cpp
Labels: bug, breaks compatibility

#795 Fix osx/ios ci
  .github/workflows/ios-ci.yml
  .github/workflows/osx-ci.yml
  .github/workflows/pr-ci.yml
Labels: gh actions

#816 Update SpritePolygonTest.cpp (fix for #231)
  tests/cpp-tests/Classes/SpritePolygonTest/SpritePolygonTest.cpp
Labels: documentation

#823 Clipper2 replacing clipper1
  core/2d/CCAutoPolygon.cpp
  core/2d/CCAutoPolygon.h
  thirdparty/CMakeLists.txt
  thirdparty/README.md
  thirdparty/clipper/CMakeLists.txt
  thirdparty/clipper/clipper.cpp
  thirdparty/clipper/clipper.hpp
  thirdparty/clipper2/CMakeLists.txt
  thirdparty/clipper2/clipper.core.h
  thirdparty/clipper2/clipper.engine.cpp
  thirdparty/clipper2/clipper.engine.h
  thirdparty/clipper2/clipper.h
  thirdparty/clipper2/clipper.minkowski.h
  thirdparty/clipper2/clipper.offset.cpp
  thirdparty/clipper2/clipper.offset.h
Labels: enhancement
