Repository axmolengine/axmol, pull requests merged in 2022-09, with the labels that each got.

#837 #825
  core/2d/CCAnimationCache.cpp
  core/2d/CCFastTMXTiledMap.cpp
  core/2d/CCFontFNT.cpp
  core/2d/CCNode.cpp
  core/2d/CCParticleBatchNode.cpp
  core/2d/CCParticleSystem.cpp
  core/2d/CCParticleSystemQuad.cpp
  core/2d/CCPlistSpriteSheetLoader.cpp
  core/2d/CCProtectedNode.cpp
  core/2d/CCSpriteBatchNode.cpp
  core/2d/CCSpriteFrameCache.cpp
  core/2d/CCTMXXMLParser.cpp
  core/2d/CCTileMapAtlas.cpp
  core/3d/CCMeshMaterial.cpp
  core/3d/CCVertexAttribBinding.cpp
  core/base/CCDirector.cpp
  core/base/ZipUtils.cpp
  core/base/ccCArray.cpp
  core/platform/CCFileUtils.cpp
  core/platform/CCImage.cpp
  core/platform/CCSAXParser.cpp
  core/renderer/CCQuadCommand.cpp
  core/renderer/CCTexture2D.cpp
  core/renderer/CCTextureAtlas.cpp
  core/renderer/CCTextureCache.cpp
  core/renderer/backend/ProgramCache.cpp
  core/renderer/backend/ShaderCache.cpp
  core/renderer/backend/opengl/ProgramGL.cpp
  tests/lua-tests/project/Classes/lua_assetsmanager_test_sample.cpp
Labels: enhancement

#844 Update Issue829Test (DrawPrimitiveTest)
  tests/cpp-tests/Classes/DrawPrimitivesTest/DrawPrimitivesTest.cpp
  tests/cpp-tests/Classes/DrawPrimitivesTest/DrawPrimitivesTest.h
Labels: cpp-tests

#863 Refactor VertexLayout sharing mechanism, fix issue #861
  core/2d/CCAtlasNode.cpp
  core/2d/CCCameraBackgroundBrush.cpp
  core/2d/CCDrawNode.cpp
  core/2d/CCFastTMXLayer.cpp
  core/2d/CCGrid.cpp
  core/2d/CCLabel.cpp
  core/2d/CCLayer.cpp
  core/2d/CCMotionStreak.cpp
  core/2d/CCParticleBatchNode.cpp
  core/2d/CCParticleSystemQuad.cpp
  core/2d/CCProgressTimer.cpp
  core/2d/CCSprite.cpp
  core/2d/CCSpriteBatchNode.cpp
  core/3d/CCMesh.cpp
  core/3d/CCMotionStreak3D.cpp
  core/3d/CCSkybox.cpp
  core/3d/CCTerrain.cpp
  core/3d/CCVertexAttribBinding.cpp
  core/3d/CCVertexAttribBinding.h
  core/base/CCStencilStateManager.cpp
  core/base/ccTypes.h
  core/navmesh/CCNavMeshDebugDraw.cpp
  core/physics3d/CCPhysics3DDebugDrawer.cpp
  core/renderer/CCTexture2D.cpp
  core/renderer/backend/Program.cpp
  core/renderer/backend/Program.h
  core/renderer/backend/ProgramCache.cpp
  core/renderer/backend/ProgramCache.h
  core/renderer/backend/ProgramState.cpp
  core/renderer/backend/ProgramState.h
  core/renderer/backend/ShaderModule.h
  core/renderer/backend/Types.h
  core/renderer/backend/VertexLayout.cpp
  core/renderer/backend/VertexLayout.h
  core/renderer/backend/metal/ProgramMTL.h
  core/renderer/backend/metal/ProgramMTL.mm
  core/renderer/backend/metal/ShaderModuleMTL.h
  core/renderer/backend/metal/ShaderModuleMTL.mm
  core/renderer/backend/opengl/ProgramGL.cpp
  core/renderer/backend/opengl/ProgramGL.h
  core/ui/UIVideoPlayer/UIVideoPlayer-win.cpp
  extensions/ImGui/imgui_impl_axys.cpp
  extensions/Live2D/Framework/src/Rendering/axys/CubismRenderer_Cocos2dx.cpp
  extensions/Particle3D/CCParticle3DRender.cpp
  extensions/Particle3D/PU/CCPUBillboardChain.cpp
  extensions/Particle3D/PU/CCPURender.cpp
  extensions/cocostudio/ActionTimeline/CCBoneNode.cpp
  extensions/cocostudio/ActionTimeline/CCSkeletonNode.cpp
  extensions/scripting/lua-bindings/auto/axlua_backend_auto.cpp
  extensions/spine/SkeletonBatch.cpp
  extensions/spine/SkeletonTwoColorBatch.cpp
  tests/cpp-tests/Classes/ClippingNodeTest/ClippingNodeTest.cpp
  tests/cpp-tests/Classes/MeshRendererTest/DrawNode3D.cpp
  tests/cpp-tests/Classes/MeshRendererTest/DrawNode3D.h
  tests/cpp-tests/Classes/NewRendererTest/NewRendererTest.cpp
  tests/cpp-tests/Classes/Physics3DTest/Physics3DTest.cpp
  tests/cpp-tests/Classes/ShaderTest/ShaderTest.cpp
  tests/live2d-tests/Classes/LAppSprite.cpp
  tests/lua-tests/project/Classes/lua_test_bindings.cpp
Labels: bug, enhancement

#874 add macro definition AX_NO_DUP_SEARCH_PATH
  core/platform/CCFileUtils.cpp
Labels: enhancement
