Repository axmolengine/axmol, pull requests merged in 2023-11, with the labels that each got.

#1414 Make AxmolEditBox invisible by default
  core/platform/android/java/src/org/axmol/lib/AxmolActivity.java
Labels: enhancement

#1409 [Android] Enable support for restarting application process if OpenGL context is lost
  core/base/EventType.h
  core/platform/PlatformMacros.h
  core/platform/android/java/src/com/jakewharton/processphoenix/ProcessPhoenix.java
  core/platform/android/java/src/org/axmol/lib/AxmolEngine.java
  core/platform/android/java/src/org/axmol/lib/AxmolRenderer.java
  core/platform/android/javaactivity-android.cpp
  core/platform/android/libaxmol/AndroidManifest.xml
Labels: enhancement

#1421 Fix for UWP build issues
  cmake/CppWinRT.props.in
  cmake/Modules/AXBuildHelpers.cmake
  core/CMakeLists.txt
Labels: bug

#1424 [UWP] Use Package to get app version information
  core/platform/winrt/Application-winrt.cpp
Labels: enhancement

#1425 Add virtual file system support to WICImageLoader
  core/platform/winrt/WICImageLoader-winrt.cpp
Labels: enhancement

#1427 [UWP] Attempt to fix issues in EditBoxWinRT
  core/ui/UIEditBox/UIEditBoxImpl-winrt.cpp
Labels: enhancement

#1434 Fix/enhancement for issue #1319 (draw filled complex polygons (concave/convex)
  core/2d/DrawNode.cpp
  tests/cpp-tests/Source/DrawPrimitivesTest/DrawPrimitivesTest.cpp
  tests/cpp-tests/Source/DrawPrimitivesTest/DrawPrimitivesTest.h
Labels: bug

#1438 Compile fix for VS2022 17.8
  thirdparty/ntcvt/ntcvt.hpp
Labels: enhancement, msvc

#1441 Improve linux deps manager
  cmake/Modules/AXConfigDepend.cmake
  cmake/Modules/AXLinkHelpers.cmake
  cmake/Modules/FindChipmunk.cmake
  cmake/Modules/FindFontconfig.cmake
  cmake/Modules/FindGTK3.cmake
  cmake/Modules/Findflatbuffers.cmake
  core/2d/Font.h
  core/platform/linux/Device-linux.cpp
  core/ui/UIEditBox/UIEditBoxImpl-linux.cpp
  setup.ps1
  tests/cpp-tests/CMakeLists.txt
  tests/cpp-tests/Source/UITest/CocoStudioGUITest/CocosGUIScene.cpp
  thirdparty/CMakeLists.txt
  thirdparty/glfw/src/CMakeLists.txt
  thirdparty/unzip/CMakeLists.txt
Labels: enhancement

#1450 Use execute_process instead of deprecated exec_program
  core/CMakeLists.txt
Labels: enhancement

#1455 Remove duplicated libz for ios/tvos
  cmake/Modules/AXConfigDepend.cmake
Labels: enhancement

#1456 new portrait splash, cmake bundle id replace, support for ipad, bette…
  templates/cpp-template-default/CMakeLists.txt
  templates/cpp-template-default/axproj-template.json
  templates/cpp-template-default/proj.ios_mac/ios/LaunchScreenBackgroundPortrait.png
  templates/cpp-template-default/proj.ios_mac/ios/targets/ios/Info.plist
  templates/lua-template-default/CMakeLists.txt
  templates/lua-template-default/axproj-template.json
  templates/lua-template-default/proj.ios_mac/ios/LaunchScreenBackgroundPortrait.png
  templates/lua-template-default/proj.ios_mac/ios/targets/ios/Info.plist
  tools/console/axmol.ps1
Labels: enhancement

#1465 Fix large number of generated warnings
  tests/cpp-tests/Source/DrawPrimitivesTest/DrawPrimitivesTest.cpp
Labels: cpp-tests
