Repository axmolengine/axmol, pull requests merged in 2023-12, with the labels that each got.

#1473 Add support for ActionCoroutine like Unity
  core/2d/ActionCoroutine.cpp
  core/2d/ActionCoroutine.h
  core/2d/CMakeLists.txt
  core/axmol.h
  tests/cpp-tests/Source/ActionsTest/ActionsTest.cpp
  tests/cpp-tests/Source/ActionsTest/ActionsTest.h
Labels: enhancement, cpp20

#1474 DrawNode::drawPie
  core/2d/DrawNode.cpp
  core/2d/DrawNode.h
  tests/cpp-tests/Source/DrawPrimitivesTest/DrawPrimitivesTest.cpp
  tests/cpp-tests/Source/DrawPrimitivesTest/DrawPrimitivesTest.h
Labels: enhancement

#1481 Fix ActionCoroutine callback style
  core/2d/ActionCoroutine.cpp
  core/2d/ActionCoroutine.h
  tests/.gitignore
  tests/cpp-tests/Source/ActionsTest/ActionsTest.cpp
Labels: enhancement

#1503 [Live2D] Fix cmake project generation on platforms other than Android
  extensions/Live2D/CMakeLists.txt
Labels: bug

#1504 Call Android native renderer while opengl context is still valid
  core/platform/android/java/src/org/axmol/lib/AxmolRenderer.java
Labels: enhancement

#1523 GLES3: Fix scalar array layout
  1k/build.ps1
  core/platform/android/libaxmol/axutils.gradle
  core/renderer/shaders/base.glsl
  core/renderer/shaders/colorNormal.frag
  core/renderer/shaders/colorNormalTexture.frag
  core/renderer/shaders/skinPositionNormalTexture.vert
  core/renderer/shaders/terrain.frag
  tests/cpp-tests/Source/shaders/color_normal_tex.frag
  tests/cpp-tests/Source/shaders/position_normal_tex.vert
  thirdparty/c-ares/CMakeLists.txt
Labels: bug

#1549 Fix issue #1546 of UILayout
  core/ui/UILayout.cpp
Labels: bug, cocos2dx

#1536 Add websocket support
  core/network/CMakeLists.txt
  core/network/WebSocket-wasm.cpp
  core/network/WebSocket-wasm.h
  core/network/WebSocket.cpp
  core/network/WebSocket.h
  tests/cpp-tests/CMakeLists.txt
  tests/cpp-tests/Source/NetworkTest/NetworkTest.cpp
  tests/cpp-tests/Source/NetworkTest/WebSocketTest/WebSocketTest.cpp
  tests/cpp-tests/Source/NetworkTest/WebSocketTest/WebSocketTest.h
  thirdparty/CMakeLists.txt
  thirdparty/websocket-parser/CMakeLists.txt
  thirdparty/websocket-parser/websocket_parser.c
  thirdparty/websocket-parser/websocket_parser.h
Labels: enhancement
