Repository axmolengine/axmol, pull requests merged in 2023-10, with the labels that each got.

#1285 Update FastTMXLayer.cpp (see issue #1283)
  core/2d/FastTMXLayer.cpp
Labels: pinned

#1392 Support adding custom properties to the inspector for derived types
  extensions/Inspector/Inspector.cpp
  extensions/Inspector/Inspector.h
Labels: enhancement

#1401 [Android] Reset the OpenGL state cache if the context is lost
  core/platform/android/javaactivity-android.cpp
  core/renderer/backend/Device.h
  core/renderer/backend/opengl/DeviceGL.cpp
  core/renderer/backend/opengl/DeviceGL.h
  core/renderer/backend/opengl/OpenGLState.cpp
  core/renderer/backend/opengl/OpenGLState.h
Labels: enhancement

#1405 Update Live2D to work with Axmol 2.x
  extensions/Live2D/CMakeLists.txt
  extensions/Live2D/Framework/src/Rendering/axmol/CubismRenderer_Cocos2dx.cpp
  extensions/Live2D/Framework/src/Rendering/axmol/CubismRenderer_Cocos2dx.hpp
  extensions/Live2D/Framework/src/Rendering/axmol/shaders/live2d.frag
  extensions/Live2D/Framework/src/Rendering/axmol/shaders/live2d.vert
  extensions/Live2D/Framework/src/Rendering/axmol/shaders/live2d_mask.frag
  extensions/Live2D/Framework/src/Rendering/axmol/shaders/live2d_mask_inverted.frag
  extensions/Live2D/Framework/src/Rendering/axmol/shaders/live2d_mask_inverted_premultiplied_alpha.frag
  extensions/Live2D/Framework/src/Rendering/axmol/shaders/live2d_mask_premultiplied_alpha.frag
  extensions/Live2D/Framework/src/Rendering/axmol/shaders/live2d_masked.vert
  extensions/Live2D/Framework/src/Rendering/axmol/shaders/live2d_premultiplied_alpha.frag
  extensions/Live2D/Framework/src/Rendering/axmol/shaders/live2d_setup_mask.frag
  extensions/Live2D/Framework/src/Rendering/axmol/shaders/live2d_setup_mask.vert
  extensions/Live2D/Framework/src/Rendering/axmol/shaders_tegra/live2d_mask_inverted_premultiplied_alpha_tegra.frag
  extensions/Live2D/Framework/src/Rendering/axmol/shaders_tegra/live2d_mask_inverted_tegra.frag
  extensions/Live2D/Framework/src/Rendering/axmol/shaders_tegra/live2d_mask_premultiplied_alpha_tegra.frag
  extensions/Live2D/Framework/src/Rendering/axmol/shaders_tegra/live2d_mask_tegra.frag
  extensions/Live2D/Framework/src/Rendering/axmol/shaders_tegra/live2d_premultiplied_alpha_tegra.frag
  extensions/Live2D/Framework/src/Rendering/axmol/shaders_tegra/live2d_setup_mask_tegra.frag
  extensions/Live2D/Framework/src/Rendering/axmol/shaders_tegra/live2d_tegra.frag
  tests/live2d-tests/CMakeLists.txt
  tests/live2d-tests/Source/LAppLive2DManager.cpp
  tests/live2d-tests/Source/LAppSprite.cpp
  tests/live2d-tests/Source/shaders/live2d_test.frag
  tests/live2d-tests/Source/shaders/live2d_test.vert
Labels: bug, enhancement
