Repository axmolengine/axmol, pull requests merged in 2024-01, with the labels that each got.

#1610 Allow to override AX_USE_COMPAT_GL from user's CMakeLists.txt
  cmake/Modules/AXPlatform.cmake
  core/CMakeLists.txt
Labels: bug, cmake

#1618 Fix AudioPlayer seek to incorrect frame after setTime invoked
  core/audio/AudioPlayer.cpp
Labels: bug

#1620 Enable default aidl file to project especially for In-app purchases
  templates/cpp-template-default/proj.android/app/build.gradle
  templates/lua-template-default/proj.android/app/build.gradle
Labels: enhancement

#1621 Prepare release 2.1.0 finally
  .github/FUNDING.yml
  1k/build.ps1
  CHANGELOG.md
  cmake/Modules/AXConfigDefine.cmake
  setup.ps1
  templates/cpp-template-default/proj.android/app/build.gradle
  templates/cpp-template-default/proj.android/gradle.properties
  templates/lua-template-default/proj.android/app/build.gradle
  templates/lua-template-default/proj.android/gradle.properties
  tests/cpp-tests/proj.android/app/build.gradle
  tests/cpp-tests/proj.android/gradle.properties
  tests/fairygui-tests/proj.android/app/build.gradle
  tests/fairygui-tests/proj.android/gradle.properties
  tests/live2d-tests/proj.android/app/build.gradle
  tests/live2d-tests/proj.android/gradle.properties
  tests/lua-tests/proj.android/app/build.gradle
  tests/lua-tests/proj.android/gradle.properties
  tools/console/axmol.ps1
  tools/console/axmol_new.ps1
Labels: enhancement, platform:android

#1631 Fix shaders not copying to final build on macOS for non Xcode builds
  cmake/Modules/AXBuildHelpers.cmake
Labels: enhancement

#1638 Fix memory leaks refreshed
  core/2d/AnimationCache.cpp
  core/2d/AnimationCache.h
  core/2d/ParticleSystem.h
  core/2d/SpriteFrameCache.cpp
  core/2d/SpriteFrameCache.h
  core/base/Configuration.cpp
  core/base/Configuration.h
  core/base/Director.cpp
  core/base/Director.h
  core/base/Profiling.h
  core/platform/ApplicationBase.cpp
  core/platform/ApplicationBase.h
  core/platform/CMakeLists.txt
  core/platform/android/Application-android.h
  core/platform/android/EnhanceAPI-android.h
  core/platform/ios/Application-ios.h
  core/platform/linux/Application-linux.h
  core/platform/mac/Application-mac.h
  core/platform/wasm/Application-wasm.h
  core/platform/win32/Application-win32.cpp
  core/platform/win32/Application-win32.h
  core/platform/winrt/Application-winrt.cpp
  core/platform/winrt/Application-winrt.h
  core/renderer/QuadCommand.cpp
  core/renderer/QuadCommand.h
  core/renderer/backend/DriverBase.h
  core/renderer/backend/ProgramManager.cpp
  core/renderer/backend/ProgramManager.h
  core/renderer/backend/ProgramStateRegistry.cpp
  core/renderer/backend/ProgramStateRegistry.h
  core/renderer/backend/ShaderCache.cpp
  core/renderer/backend/ShaderCache.h
  core/renderer/backend/metal/DriverMTL.mm
  core/renderer/backend/opengl/DriverGL.cpp
  extensions/scripting/lua-bindings/script/core/Constants.lua
Labels: bug
