Repository axmolengine/axmol, pull requests merged in 2024-04, with the labels that each got.

#1786 Add apple xcframework support
  1k/fetch.cmake
  3rdparty/CMakeLists.txt
  3rdparty/README.md
  3rdparty/c-ares/CMakeLists.txt
  3rdparty/curl/CMakeLists.txt
  3rdparty/jpeg-turbo/CMakeLists.txt
  3rdparty/lua/luajit/CMakeLists.txt
  3rdparty/openssl/CMakeLists.txt
  3rdparty/zlib/CMakeLists.txt
  CHANGELOG.md
  manifest.json
Labels: enhancement

#1788 Add CMake option to remove Console from builds
  CMakeOptions.md
  core/3d/BundleReader.h
  core/CMakeLists.txt
  core/audio/AudioDecoderManager.cpp
  core/audio/AudioDecoderMp3.cpp
  core/axmol.h
  core/base/CMakeLists.txt
  core/base/Console.h
  core/base/Data.cpp
  core/base/Director.cpp
  core/base/Director.h
  core/base/EventListener.cpp
  core/base/EventListenerAcceleration.cpp
  core/base/Macros.h
  core/base/UTF8.cpp
  core/media/MediaEngine.h
  core/network/IDownloaderImpl.h
  core/network/Uri.cpp
  core/network/WebSocket-wasm.cpp
  core/platform/ios/Common-ios.mm
  core/platform/linux/Common-linux.cpp
  core/platform/wasm/Common-wasm.cpp
  core/renderer/Material.cpp
Labels: enhancement

#1803 Update to 3rdparty v82
  3rdparty/CMakeLists.txt
  3rdparty/openssl/CMakeLists.txt
  manifest.json
Labels: enhancement

#1808 Fix same uniforms in fragment and vertex shaders not working in Metal
  core/renderer/backend/ProgramState.cpp
  core/renderer/backend/ProgramState.h
  core/renderer/backend/Types.cpp
  core/renderer/backend/Types.h
  core/renderer/backend/metal/ProgramMTL.mm
  core/renderer/backend/metal/ShaderModuleMTL.h
  core/renderer/backend/metal/ShaderModuleMTL.mm
  core/renderer/backend/opengl/ProgramGL.cpp
  core/renderer/shaders/positionNormalTexture.vert
  extensions/scripting/lua-bindings/manual/LuaBasicConversions.cpp
Labels: bug, enhancement

#1823 Improve MediaPlayer: handle video rotation properly
  core/media/AndroidMediaEngine.cpp
  core/media/AndroidMediaEngine.h
  core/media/AvfMediaEngine.h
  core/media/AvfMediaEngine.mm
  core/media/MediaEngine.h
  core/media/VlcMediaEngine.cpp
  core/media/WmfMediaEngine.cpp
  core/media/WmfMediaEngine.h
  core/platform/android/java/src/org/axmol/lib/AxmolMediaEngine.java
  core/platform/android/java/src/org/axmol/lib/MediaCodecVideoRenderer.java
  core/ui/UIMediaPlayer.cpp
Labels: enhancement

#1830 Fixed an issue where ProgressTimer didn't properly set or cascade its opacity
  core/2d/ProgressTimer.cpp
  core/2d/ProgressTimer.h
Labels: enhancement

#1837 Fix failed assertion and memory leak with event listeners
  core/2d/Node.cpp
Labels: bug, breaks compatibility

#1839 Remove deprecated pixel formats L8, A8, LA8
  core/2d/FontAtlas.cpp
  core/2d/PlistSpriteSheetLoader.cpp
  core/3d/Terrain.cpp
  core/platform/Image.cpp
  core/renderer/Texture2D.cpp
  core/renderer/backend/Enums.h
  core/renderer/backend/PixelFormatUtils.cpp
  core/renderer/backend/PixelFormatUtils.h
  core/renderer/backend/metal/UtilsMTL.mm
  core/renderer/backend/opengl/UtilsGL.cpp
  core/renderer/shaders/base.glsl
  core/renderer/shaders/label_distanceGlow.frag
  core/renderer/shaders/label_distanceNormal.frag
  core/renderer/shaders/label_distanceOutline.frag
  core/renderer/shaders/label_normal.frag
  core/renderer/shaders/videoTextureNV12.frag
  core/ui/UIMediaPlayer.cpp
  extensions/ImGui/shaders/imgui_font.frag
  extensions/ImGui/src/ImGui/imgui_impl_ax.cpp
  extensions/ImGui/src/ImGui/imgui_impl_ax_android.cpp
  extensions/scripting/lua-bindings/auto/axlua_backend_auto.cpp
  extensions/scripting/lua-bindings/script/core/Constants.lua
  tests/cpp-tests/Source/SpriteFrameCacheTest/SpriteFrameCacheTest.cpp
  tests/cpp-tests/Source/Texture2dTest/Texture2dTest.cpp
Labels: enhancement, breaks compatibility

#1844 When loading csb files, prevent repeated loading of plist files
  core/2d/SpriteFrameCache.cpp
  core/2d/SpriteFrameCache.h
  extensions/cocostudio/src/cocostudio/ActionTimeline/CSLoader.cpp
Labels: enhancement

#1845 Cross-platform media controller for video playback
  1k/fetch.ps1
  cmake/Modules/AXBuildHelpers.cmake
  core/CMakeLists.txt
  core/media/AndroidMediaEngine.cpp
  core/media/AndroidMediaEngine.h
  core/media/AvfMediaEngine.h
  core/media/AvfMediaEngine.mm
  core/media/MediaEngine.cpp
  core/media/MediaEngine.h
  core/media/MfMediaEngine.cpp
  core/media/MfMediaEngine.h
  core/media/VlcMediaEngine.cpp
  core/media/VlcMediaEngine.h
  core/media/WmfMediaEngine.cpp
  core/media/WmfMediaEngine.h
  core/platform/android/java/src/org/axmol/lib/AxmolMediaEngine.java
  core/ui/CMakeLists.txt
  core/ui/UIMediaPlayer.cpp
  core/ui/UIMediaPlayer.h
  core/ui/axmol-ui.h
  tests/cpp-tests/CMakeLists.txt
  tests/cpp-tests/Source/UITest/CocoStudioGUITest/CocosGUIScene.cpp
Labels: enhancement, media

#1847 Cleanup cc stubs
  core/2d/Grid.cpp
  core/2d/RenderTexture.cpp
  core/base/Utils.cpp
  core/base/Utils.h
  core/platform/Common.h
  core/platform/GLViewImpl.cpp
  core/platform/Image.cpp
  core/platform/android/Common-android.cpp
  core/platform/ios/Common-ios.mm
  core/platform/linux/Common-linux.cpp
  core/platform/mac/Common-mac.mm
  core/platform/wasm/Common-wasm.cpp
  core/platform/win32/Common-win32.cpp
  core/platform/winrt/Common-winrt.cpp
  core/renderer/Texture2D.cpp
  core/renderer/backend/opengl/DriverGL.cpp
  extensions/Effekseer/EffekseerForCocos2d-x/EffekseerForCocos2d-x.cpp
Labels: enhancement, breaks compatibility

#1848 [Apple] Fix media controls not appearing
  core/ui/UIMediaPlayer.cpp
  core/ui/UIMediaPlayer.h
Labels: enhancement

#1849 Fix Upload to MacAppStore
  templates/cpp/CMakeLists.txt
Labels: bug

#1851 Adjust media control positioning if video aspect ratio is maintained
  core/ui/UIMediaPlayer.cpp
Labels: bug

#1859 Add ability to create console apps
  1k/build.ps1
  cmake/Modules/AXBuildHelpers.cmake
  templates/common/proj.win32/main.cpp
  tests/cpp-tests/proj.win32/main.cpp
  tests/fairygui-tests/proj.win32/main.cpp
  tests/live2d-tests/proj.win32/main.cpp
  tests/lua-tests/CMakeLists.txt
  tests/lua-tests/Source/AppDelegate.cpp
  tests/lua-tests/proj.win32/main.cpp
Labels: enhancement

#1867 Update documentation to reflect latest changes
  docs/DevSetup.md
Labels: documentation
