Repository axmolengine/axmol, pull requests merged in 2024-09, with the labels that each got.

#2138 Fix for incorrect bits per pixel set on texture reload
  core/renderer/Texture2D.cpp
  core/renderer/TextureCache.cpp
  core/renderer/TextureCache.h
  core/renderer/backend/Texture.cpp
  core/renderer/backend/opengl/TextureGL.cpp
Labels: bug

#2141 Fix EventMouse coords
  core/base/EventMouse.cpp
  core/base/EventMouse.h
  core/platform/GLView.cpp
  core/platform/GLView.h
  core/platform/GLViewImpl.cpp
  core/platform/winrt/GLViewImpl-winrt.cpp
  core/platform/winrt/GLViewImpl-winrt.h
  extensions/scripting/lua-bindings/auto/axlua_base_auto.cpp
Labels: bug

#2149 No longer add sprite as child of RenderTexture
  core/2d/RenderTexture.cpp
Labels: breaks compatibility

#2148 Fix RenderTargetGL FBO not recreate when recv EVENT_RENDERER_RECREATED
  core/renderer/backend/opengl/RenderTargetGL.cpp
  core/renderer/backend/opengl/RenderTargetGL.h
  core/renderer/backend/opengl/TextureGL.cpp
  core/renderer/backend/opengl/TextureGL.h
Labels: bug

#2159 Fix LuaJit Compilations
  3rdparty/lua/lua-cjson/CMakeLists.txt
  3rdparty/lua/tolua/CMakeLists.txt
  extensions/scripting/lua-bindings/manual/LuaBasicConversions.cpp
Labels: bug, enhancement

#2162 [Android] Fix fps issue when certain animation intervals are set
  core/platform/android/java/src/org/axmol/lib/AxmolRenderer.java
Labels: bug
