Repository axmolengine/axmol, pull requests merged in 2024-06, with the labels that each got.

#1967 Sprite and TextureCache from ax::Data
  core/2d/Sprite.cpp
  core/2d/Sprite.h
  core/renderer/TextureCache.cpp
  core/renderer/TextureCache.h
  tests/cpp-tests/Source/SpriteTest/SpriteTest.cpp
  tests/cpp-tests/Source/SpriteTest/SpriteTest.h
Labels: enhancement

#1968 Add JobSystem support
  .github/workflows/build.yml
  CHANGELOG.md
  core/2d/RenderTexture.cpp
  core/3d/MeshRenderer.cpp
  core/audio/AudioEngine.cpp
  core/audio/AudioEngine.h
  core/audio/AudioPlayer.cpp
  core/base/CMakeLists.txt
  core/base/Director.cpp
  core/base/Director.h
  core/base/JobSystem.cpp
  core/base/JobSystem.h
  core/base/Utils.cpp
  core/base/astc.cpp
  core/media/WmfMediaEngine.cpp
  core/platform/FileUtils.h
  extensions/assets-manager/src/assets-manager/AssetsManagerEx.cpp
Labels: enhancement

#1942 Only pause GLSurfaceView if activity is moved to the background, and not if it just loses focus
  core/platform/android/java/src/org/axmol/lib/AxmolActivity.java
  core/platform/android/java/src/org/axmol/lib/AxmolGLSurfaceView.java
  core/platform/android/java/src/org/axmol/lib/AxmolRenderer.java
  core/platform/android/jni/Java_org_axmol_lib_AxmolRenderer.cpp
Labels: enhancement

#1985 Linux WebView implementation
  core/CMakeLists.txt
  core/platform/GLView.h
  core/platform/GLViewImpl.cpp
  core/platform/GLViewImpl.h
  core/ui/CMakeLists.txt
  core/ui/UIWebView/UIWebView-inl.h
  core/ui/UIWebView/UIWebView.cpp
  core/ui/UIWebView/UIWebView.h
  core/ui/UIWebView/UIWebViewCommon.h
  core/ui/UIWebView/UIWebViewImpl-linux.cpp
  core/ui/UIWebView/UIWebViewImpl-linux.h
  core/ui/UIWebView/UIWebViewImpl-win32.cpp
  setup.ps1
  tests/cpp-tests/Source/UITest/CocoStudioGUITest/CocosGUIScene.cpp
Labels: enhancement

#1981 Rendering fixes
  core/2d/Grid.cpp
  core/2d/RenderTexture.cpp
  core/2d/RenderTexture.h
  core/base/Types.h
  core/renderer/Renderer.cpp
  core/renderer/Renderer.h
  core/renderer/backend/DepthStencilState.h
  core/renderer/backend/DriverBase.h
  core/renderer/backend/RenderTarget.h
  core/renderer/backend/Types.h
  core/renderer/backend/metal/CommandBufferMTL.h
  core/renderer/backend/metal/CommandBufferMTL.mm
  core/renderer/backend/metal/DepthStencilStateMTL.h
  core/renderer/backend/metal/DepthStencilStateMTL.mm
  core/renderer/backend/metal/DriverMTL.h
  core/renderer/backend/metal/DriverMTL.mm
  core/renderer/backend/metal/RenderPipelineMTL.mm
  core/renderer/backend/metal/RenderTargetMTL.mm
  core/renderer/backend/opengl/DriverGL.cpp
  core/renderer/backend/opengl/DriverGL.h
  core/renderer/backend/opengl/RenderTargetGL.cpp
  extensions/scripting/lua-bindings/auto/axlua_backend_auto.cpp
  extensions/scripting/lua-bindings/auto/axlua_base_auto.cpp
Labels: enhancement, needs-test

#1992 Don't output log when custom ILogOutput was set
  core/base/Logging.cpp
  core/base/Logging.h
Labels: enhancement, breaks compatibility

#1995 Use new logging system for audio
  core/audio/AudioCache.cpp
  core/audio/AudioDecoderMp3.cpp
  core/audio/AudioDecoderOgg.cpp
  core/audio/AudioDecoderWav.cpp
  core/audio/AudioEngineImpl.cpp
  core/audio/AudioMacros.h
  core/audio/AudioPlayer.cpp
  core/base/Logging.cpp
  core/base/Logging.h
Labels: enhancement

#1999 Improve curl downloader
  core/network/Downloader-curl.cpp
  tests/cpp-tests/Source/NetworkTest/DownloaderTest/DownloaderTest.cpp
Labels: enhancement

#2008 DrawNodeV2 0.94 (currently DrawNodeEx)
  extensions/DrawNodeEx/src/DrawNodeEx/DrawNodeEx.cpp
  extensions/DrawNodeEx/src/DrawNodeEx/DrawNodeEx.h
  tests/cpp-tests/Source/DrawNodeExTest/DrawNodeExTest.cpp
  tests/cpp-tests/Source/DrawNodeExTest/DrawNodeExTest.h
Labels: enhancement

#1996 Renderer fixes
  core/2d/Grid.cpp
  core/2d/RenderTexture.cpp
  core/2d/RenderTexture.h
  core/base/Types.h
  core/renderer/Renderer.cpp
  core/renderer/Renderer.h
  core/renderer/backend/DepthStencilState.h
  core/renderer/backend/DriverBase.h
  core/renderer/backend/RenderTarget.h
  core/renderer/backend/Types.h
  core/renderer/backend/metal/CommandBufferMTL.h
  core/renderer/backend/metal/CommandBufferMTL.mm
  core/renderer/backend/metal/DepthStencilStateMTL.h
  core/renderer/backend/metal/DepthStencilStateMTL.mm
  core/renderer/backend/metal/DriverMTL.h
  core/renderer/backend/metal/DriverMTL.mm
  core/renderer/backend/metal/RenderPipelineMTL.mm
  core/renderer/backend/metal/RenderTargetMTL.mm
  core/renderer/backend/opengl/DriverGL.cpp
  core/renderer/backend/opengl/DriverGL.h
  core/renderer/backend/opengl/RenderTargetGL.cpp
  extensions/scripting/lua-bindings/auto/axlua_backend_auto.cpp
  extensions/scripting/lua-bindings/auto/axlua_base_auto.cpp
Labels: enhancement
