Repository axmolengine/axmol, pull requests merged in 2024-05, with the labels that each got.

#1871 Enable running `unit-tests` in GitHub workflow
  .github/workflows/build.yml
  tests/unit-tests/Source/AppDelegate.cpp
  tests/unit-tests/Source/core/platform/FileUtilsTests.cpp
  tools/cmdline/axmol.ps1
Labels: enhancement

#1875 [Spine] Fix two color tint data not being copied across to backend buffer on first frame
  extensions/spine/src/spine/SkeletonRenderer.cpp
Labels: spine-runtime

#1883 Bring the latest extension::DrawNodeEx to axmol
  extensions/DrawNodeEx/src/DrawNodeEx/DrawNodeEx.cpp
  extensions/DrawNodeEx/src/DrawNodeEx/DrawNodeEx.h
Labels: enhancement

#1890 Retain _debugDrawNode in Label
  core/2d/Label.cpp
Labels: bug

#1897 Add support for ensuring sprite content size does not change on new texture
  core/2d/Sprite.cpp
  core/2d/Sprite.h
Labels: enhancement

#1908 Fix shaders not copying to final build on macOS for non Xcode builds (2)
  cmake/Modules/AXBuildHelpers.cmake
  cmake/Modules/AXConfigDefine.cmake
  cmake/Modules/AXGLSLCC.cmake
  templates/cpp/CMakeLists.txt
  templates/lua/CMakeLists.txt
  tests/cpp-tests/CMakeLists.txt
  tests/fairygui-tests/CMakeLists.txt
  tests/live2d-tests/CMakeLists.txt
  tests/lua-tests/CMakeLists.txt
  tests/unit-tests/CMakeLists.txt
Labels: enhancement

#1919 [Android] Add x86_64 to example list of possible target architectures
  templates/common/proj.android/gradle.properties
  tests/cpp-tests/proj.android/gradle.properties
  tests/fairygui-tests/proj.android/gradle.properties
  tests/live2d-tests/proj.android/gradle.properties
  tests/lua-tests/proj.android/gradle.properties
  tests/unit-tests/proj.android/gradle.properties
Labels: enhancement

#1918 [Android] Update the CMake minimum version requirement to 3.23.0+
  core/platform/android/libaxmol/axutils.gradle
Labels: enhancement

#1920 [Android] Fix ImGui usage crash due to invalid pointer
  extensions/ImGui/src/ImGui/imgui_impl_ax_android.cpp
Labels: bug

#1916 Set AX_USE_METAL and AX_USE_GL to 1 if defined
  core/platform/PlatformConfig.h
Labels: enhancement

#1924 Fix passing non null terminated strings for null terminated params
  core/media/AvfMediaEngine.mm
  core/platform/apple/FileUtils-apple.mm
  core/platform/ios/Device-ios.mm
  core/platform/mac/Device-mac.mm
Labels: enhancement

#1929 Do image processing to reverse premultiplied alpha in separate thread
  core/2d/RenderTexture.cpp
  core/2d/RenderTexture.h
Labels: enhancement

#1932 Add ability to change Inspector's font size
  extensions/Inspector/src/Inspector/Inspector.cpp
  extensions/Inspector/src/Inspector/Inspector.h
Labels: enhancement

#1934 [Android] Calculate safe area inset values for devices with rounded corners
  core/platform/android/GLViewImpl-android.cpp
  core/platform/android/java/src/org/axmol/lib/AxmolEngine.java
  core/platform/android/jni/JniHelper.h
Labels: enhancement

#1938 Update documentation for axmol build commands when targetting the iOS simulator
  docs/DevSetup.md
Labels: documentation

#1936 Added glyph ranges manager for ImGuiPresenter, added ability to use glyph ranges for Inspector's font
  extensions/ImGui/src/ImGui/ImGuiPresenter.cpp
  extensions/ImGui/src/ImGui/ImGuiPresenter.h
  extensions/ImGui/src/ImGui/README.md
  extensions/Inspector/src/Inspector/Inspector.cpp
  extensions/Inspector/src/Inspector/Inspector.h
  extensions/SDFGen/src/SDFGen/SDFGen.cpp
Labels: enhancement

#1940 Add support for necessary events to be sent regardless of event dispatcher enabled state
  core/base/EventDispatcher.cpp
  core/base/EventDispatcher.h
  core/platform/android/javaactivity-android.cpp
  core/platform/android/jni/Java_org_axmol_lib_AxmolRenderer.cpp
  core/platform/winrt/xaml/AxmolRenderer.cpp
  tests/cpp-tests/Source/NewEventDispatcherTest/NewEventDispatcherTest.cpp
Labels: bug, enhancement
