Repository axmolengine/axmol, pull requests merged in 2025-07, with the labels that each got.

#2579 Add close code and reason for Websocket close / onClose
  core/network/WebSocket-wasm.cpp
  core/network/WebSocket-wasm.h
  core/network/WebSocket.cpp
  core/network/WebSocket.h
  extensions/scripting/lua-bindings/manual/network/lua_websocket.cpp
  extensions/scripting/lua-bindings/manual/network/lua_websocket.h
  tests/cpp-tests/Source/NetworkTest/WebSocketTest/WebSocketTest.cpp
  tests/cpp-tests/Source/NetworkTest/WebSocketTest/WebSocketTest.h
Labels: enhancement

#2584 Update ImGui to 1.92.0 and refactor imgui axmol backend
  core/platform/GLViewImpl.h
  core/renderer/backend/opengl/TextureGL.cpp
  extensions/ImGui/CMakeLists.txt
  extensions/ImGui/shaders/imgui_font.frag
  extensions/ImGui/shaders/imgui_sprite.vert
  extensions/ImGui/src/ImGui/ImGuiPresenter.cpp
  extensions/ImGui/src/ImGui/ImGuiPresenter.h
  extensions/ImGui/src/ImGui/LICENSE
  extensions/ImGui/src/ImGui/imgui/LICENSE.txt
  extensions/ImGui/src/ImGui/imgui/imconfig.h
  extensions/ImGui/src/ImGui/imgui/imgui.cpp
  extensions/ImGui/src/ImGui/imgui/imgui.h
  extensions/ImGui/src/ImGui/imgui/imgui_demo.cpp
  extensions/ImGui/src/ImGui/imgui/imgui_draw.cpp
  extensions/ImGui/src/ImGui/imgui/imgui_internal.h
  extensions/ImGui/src/ImGui/imgui/imgui_tables.cpp
  extensions/ImGui/src/ImGui/imgui/imgui_widgets.cpp
  extensions/ImGui/src/ImGui/imgui/imstb_textedit.h
  extensions/ImGui/src/ImGui/imgui/imstb_truetype.h
  extensions/ImGui/src/ImGui/imgui/misc/cpp/README.txt
  extensions/ImGui/src/ImGui/imgui/misc/cpp/imgui_stdlib.cpp
  extensions/ImGui/src/ImGui/imgui/misc/cpp/imgui_stdlib.h
  extensions/ImGui/src/ImGui/imgui/misc/freetype/imgui_freetype.cpp
  extensions/ImGui/src/ImGui/imgui/misc/freetype/imgui_freetype.h
  extensions/ImGui/src/ImGui/imgui_impl_android.cpp
  extensions/ImGui/src/ImGui/imgui_impl_android.h
  extensions/ImGui/src/ImGui/imgui_impl_ax.h
  extensions/ImGui/src/ImGui/imgui_impl_ax_android.cpp
  extensions/ImGui/src/ImGui/imgui_impl_ax_android.h
  extensions/ImGui/src/ImGui/imgui_impl_axmol.cpp
  extensions/ImGui/src/ImGui/imgui_impl_axmol.h
  extensions/ImGui/src/ImGui/imgui_impl_glfw.cpp
  extensions/ImGui/src/ImGui/imgui_impl_glfw.h
  extensions/Inspector/src/Inspector/Inspector.cpp
  extensions/Inspector/src/Inspector/Inspector.h
Labels: enhancement

#2587 Remove redundant 'cc' prefix
  core/2d/ActionCatmullRom.cpp
  core/2d/ActionCatmullRom.h
  core/2d/DrawNode.cpp
  core/2d/MotionStreak.cpp
  core/audio/AudioEngineImpl.cpp
  core/math/Vertex.cpp
  core/math/Vertex.h
Labels: enhancement

#2588 Improve android sdk setup
  1k/1kiss.ps1
  tools/cmdline/build.ps1
Labels: enhancement

#2590 Add parameter `-r` for `axmol new` command to regenerates the missing…
  templates/cpp/axproj-template.json
  templates/lua/axproj-template.json
  tools/cmdline/axmol.ps1
  tools/cmdline/axmol_new.ps1
Labels: feature proposal

#2600 Improve apple ios platform render view creation
  cmake/Modules/AXBuildHelpers.cmake
  cmake/Modules/AXConfigDefine.cmake
  cmake/Modules/AXConfigDepend.cmake
  core/2d/ClippingRectangleNode.h
  core/2d/DrawNode.cpp
  core/2d/FastTMXLayer.cpp
  core/2d/FontCharMap.cpp
  core/2d/LabelAtlas.cpp
  core/2d/Node.h
  core/2d/ParticleSystem.cpp
  core/2d/ParticleSystem.h
  core/2d/ParticleSystemQuad.cpp
  core/3d/Mesh.cpp
  core/audio/AudioDecoderOpus.cpp
  core/base/Config.h
  core/base/Console.h
  core/base/Director.cpp
  core/base/Director.h
  core/base/FPSImages.cpp
  core/base/Profiling.h
  core/base/Scheduler.h
  core/physics/PhysicsWorld.h
  core/platform/FileUtils.h
  core/platform/ios/EAGLView-ios.h
  core/platform/ios/EAGLView-ios.mm
  core/platform/ios/GLViewImpl-ios.h
  core/platform/ios/GLViewImpl-ios.mm
  core/renderer/TextureCache.h
  extensions/DragonBones/src/DragonBones/CCSlot.cpp
  extensions/cocostudio/src/cocostudio/TriggerBase.cpp
  templates/common/proj.ios_mac/ios/AppController.mm
  templates/common/proj.ios_mac/ios/RootViewController.mm
  tests/cpp-tests/Source/ActionsTest/ActionsTest.cpp
  tests/cpp-tests/Source/AppDelegate.h
  tests/cpp-tests/Source/BillBoardTest/BillBoardTest.cpp
  tests/cpp-tests/Source/Camera3DTest/Camera3DTest.cpp
  tests/cpp-tests/Source/ChipmunkTest/ChipmunkTest.cpp
  tests/cpp-tests/Source/ConsoleTest/ConsoleTest.cpp
  tests/cpp-tests/Source/CurlTest/CurlTest.cpp
  tests/cpp-tests/Source/DrawNodeTest/DrawNodeTest.cpp
  tests/cpp-tests/Source/DrawNodeTest/DrawNodeTest.h
  tests/cpp-tests/Source/NetworkTest/DownloaderTest/DownloaderTest.cpp
  tests/cpp-tests/Source/ParticleTest/ParticleTest.cpp
  tests/cpp-tests/Source/SpineTest/SpineTest.h
  tests/cpp-tests/Source/SpriteTest/SpriteTest.cpp
  tests/cpp-tests/Source/Texture2dTest/Texture2dTest.cpp
  tests/cpp-tests/Source/TextureCacheTest/TextureCacheTest.cpp
  tests/cpp-tests/Source/TouchesTest/TouchesTest.cpp
  tests/cpp-tests/Source/UITest/CocoStudioGUITest/UIScrollViewTest/UIScrollViewTest.cpp
  tests/cpp-tests/Source/UITest/CocoStudioGUITest/UITabControlTest/UITabControlTest.cpp
  tests/cpp-tests/Source/UITest/CocoStudioGUITest/UITabControlTest/UITabControlTest.h
  tests/cpp-tests/Source/UserDefaultTest/UserDefaultTest.cpp
  tests/cpp-tests/proj.ios/Source/testsAppDelegate.mm
  tests/fairygui-tests/Source/AppDelegate.h
  tests/fairygui-tests/proj.ios/AppController.mm
  tests/live2d-tests/Source/AppDelegate.h
  tests/live2d-tests/proj.ios/AppController.mm
  tests/lua-tests/Content/src/ActionsTest/ActionsTest.lua
  tests/lua-tests/proj.ios_mac/ios/AppController.mm
  tests/unit-tests/proj.ios/Source/testsAppDelegate.mm
Labels: enhancement, breaking changes

#2612 🛠 Fix incorrect fmt::format_to use case
  core/base/format.h
  tests/cpp-tests/Source/ActionsTest/ActionsTest.cpp
  tests/cpp-tests/Source/BillBoardTest/BillBoardTest.cpp
  tests/cpp-tests/Source/Camera3DTest/Camera3DTest.cpp
  tests/cpp-tests/Source/CurlTest/CurlTest.cpp
  tests/cpp-tests/Source/NetworkTest/DownloaderTest/DownloaderTest.cpp
  tests/cpp-tests/Source/NetworkTest/WebSocketTest/WebSocketTest.cpp
  tests/cpp-tests/Source/SpriteTest/SpriteTest.cpp
  tests/cpp-tests/Source/Texture2dTest/Texture2dTest.cpp
  tests/cpp-tests/Source/TextureCacheTest/TextureCacheTest.cpp
  tests/cpp-tests/Source/TouchesTest/TouchesTest.cpp
  tests/cpp-tests/Source/UserDefaultTest/UserDefaultTest.cpp
Labels: bug
