Repository axmolengine/axmol, pull requests merged in 2025-03, with the labels that each got.

#2433 [Template] Add missing override specifier to destructor
  templates/cpp/Source/MainScene.h
Labels: enhancement

#2445 Fix for invalid event listener ID lookup
  core/base/EventDispatcher.cpp
Labels: bug

#2444 Refactor SpriteFrameCache to use uint64_t as map key
  core/2d/SpriteFrame.h
  core/2d/SpriteFrameCache.cpp
  core/2d/SpriteFrameCache.h
  core/2d/SpriteSheetLoader.h
  core/base/hlookup.h
Labels: bug, enhancement

#2450 Log frame names instead of hash values in the call to removeUnusedSpriteFrames()
  core/2d/SpriteFrameCache.cpp
Labels: enhancement

#2476 DrawNode: API improvement: supporting 'closed' Splines; Update UserDefault.cpp/h (fix typo)
  core/2d/DrawNode.cpp
  core/2d/DrawNode.h
  core/base/UserDefault.cpp
  core/base/UserDefault.h
  tests/cpp-tests/Source/DrawNodeTest/DrawNodeTest.cpp
  tests/cpp-tests/Source/DrawNodeTest/DrawNodeTest.h
Labels: enhancement
