Repository axmolengine/axmol, pull requests merged in 2025-05, with the labels that each got.

#2527 Update 3rd libs
  3rdparty/README.md
  3rdparty/doctest/doctest.cpp
  3rdparty/doctest/doctest_fwd.h
  3rdparty/fmt/CMakeLists.txt
  3rdparty/fmt/ChangeLog.md
  3rdparty/fmt/README.md
  3rdparty/fmt/include/fmt/base.h
  3rdparty/fmt/include/fmt/chrono.h
  3rdparty/fmt/include/fmt/color.h
  3rdparty/fmt/include/fmt/format-inl.h
  3rdparty/fmt/include/fmt/format.h
  3rdparty/fmt/include/fmt/ostream.h
  3rdparty/fmt/include/fmt/ranges.h
  3rdparty/fmt/include/fmt/std.h
  3rdparty/fmt/include/fmt/xchar.h
  3rdparty/llhttp/include/llhttp.h
  3rdparty/llhttp/src/api.c
  3rdparty/llhttp/src/llhttp.c
  3rdparty/png/README
  3rdparty/png/arm/arm_init.c
  3rdparty/png/png.c
  3rdparty/png/png.h
  3rdparty/png/pngconf.h
  3rdparty/png/pngdebug.h
  3rdparty/png/pngerror.c
  3rdparty/png/pngget.c
  3rdparty/png/pnginfo.h
  3rdparty/png/pnglibconf.h
  3rdparty/png/pngmem.c
  3rdparty/png/pngpread.c
  3rdparty/png/pngpriv.h
  3rdparty/png/pngread.c
  3rdparty/png/pngrio.c
  3rdparty/png/pngrtran.c
  3rdparty/png/pngrutil.c
  3rdparty/png/pngset.c
  3rdparty/png/pngstruct.h
  3rdparty/png/pngwio.c
  3rdparty/png/pngwrite.c
  3rdparty/png/pngwutil.c
  tests/unit-tests/Source/TestUtils.h
Labels: enhancement

#2541 Clipper2 1.5.3
  3rdparty/README.md
  3rdparty/clipper2/include/clipper2/clipper.core.h
  3rdparty/clipper2/include/clipper2/clipper.h
  3rdparty/clipper2/include/clipper2/clipper.offset.h
  3rdparty/clipper2/include/clipper2/clipper.version.h
  3rdparty/clipper2/src/clipper.engine.cpp
  3rdparty/clipper2/src/clipper.offset.cpp
Labels: enhancement

#2544 Improve ZipUtils::decompressGZ
  core/base/ZipUtils.cpp
  core/base/ZipUtils.h
Labels: bug, enhancement

#2546 Update android devenv to support android 16
  1k/build.profiles
  CHANGELOG.md
  docs/DevSetup.md
  templates/common/proj.android/app/build.gradle
  templates/common/proj.android/build.gradle
  tests/cpp-tests/proj.android/app/build.gradle
  tests/cpp-tests/proj.android/build.gradle
  tests/fairygui-tests/proj.android/app/build.gradle
  tests/fairygui-tests/proj.android/build.gradle
  tests/live2d-tests/proj.android/app/build.gradle
  tests/live2d-tests/proj.android/build.gradle
  tests/lua-tests/proj.android/app/build.gradle
  tests/lua-tests/proj.android/build.gradle
  tests/unit-tests/proj.android/app/build.gradle
  tests/unit-tests/proj.android/build.gradle
Labels: enhancement

#2549 Fix #2548 Downloader-curl may crash or hang in download thread
  core/network/ConcurrentRefCountedBase.h
  core/network/Downloader-curl.cpp
  core/network/Downloader-curl.h
  core/network/Downloader-wasm.cpp
  core/network/Downloader-wasm.h
  core/network/Downloader.cpp
  core/network/Downloader.h
  core/network/HttpRequest.h
  core/network/HttpResponse.h
  core/network/IDownloaderImpl.h
  tests/cpp-tests/Source/NetworkTest/DownloaderTest/DownloaderTest.cpp
Labels: bug
