Repository axmolengine/axmol, pull requests merged in 2025-09, with the labels that each got.

#2675 Fix #2674 ssl not link by final app automatically
  3rdparty/CMakeLists.txt
  3rdparty/curl/CMakeLists.txt
  3rdparty/openssl/CMakeLists.txt
  3rdparty/yasio/CMakeLists.txt
Labels: enhancement, platform:linux, archlinux

#2692 ax::PointArray: Add method: clear()
  core/2d/ActionCatmullRom.cpp
  core/2d/ActionCatmullRom.h
Labels: enhancement

#2693 Revert DrawNode color param to Color4F to fix Lua test issues
  core/2d/DrawNode.cpp
  core/2d/DrawNode.h
  core/ui/UILayout.cpp
  core/ui/UIMediaPlayer.cpp
  extensions/fairygui/src/fairygui/GGraph.cpp
  extensions/fairygui/src/fairygui/GGraph.h
  extensions/physics-nodes/src/physics-nodes/PhysicsDebugNodeChipmunk2D.cpp
  extensions/scripting/lua-bindings/auto/axlua_base_auto.cpp
  extensions/scripting/lua-bindings/auto/axlua_fairygui_auto.cpp
  extensions/scripting/lua-bindings/manual/base/axlua_base_manual.cpp
  extensions/spine/src/spine/SkeletonRenderer.cpp
  tests/cpp-tests/Source/ClippingNodeTest/ClippingNodeTest.cpp
  tests/cpp-tests/Source/DrawNodeTest/DrawNodeTest.cpp
Labels: compatibility

#2750 feat(wasm): add fullscreen support for WebAssembly builds
  axmol/platform/RenderView.cpp
  axmol/platform/desktop/RenderViewImpl.cpp
  axmol/platform/desktop/RenderViewImpl.h
  axmol/rhi/opengl/CommandBufferGL.cpp
  templates/cpp/Source/AppDelegate.cpp
Labels: enhancement

#2755 [d3d11] Add V-Sync control support
  axmol/rhi/d3d/CommandBufferD3D.cpp
  axmol/rhi/d3d/CommandBufferD3D.h
Labels: enhancement

#2765 Replace some more cocos (lua) ...
  extensions/scripting/lua-bindings/manual/3d/axlua_3d_manual.cpp
  extensions/scripting/lua-bindings/manual/LuaBasicConversions.h
  extensions/scripting/lua-bindings/manual/base/LuaScriptHandlerMgr.cpp
  extensions/scripting/lua-bindings/manual/base/axlua_base_manual.cpp
  extensions/scripting/lua-bindings/manual/extension/axlua_extension_manual.cpp
  extensions/scripting/lua-bindings/manual/fairygui/axlua_fairygui_manual.cpp
  extensions/scripting/lua-bindings/manual/navmesh/axlua_navmesh_manual.cpp
  extensions/scripting/lua-bindings/manual/physics/axlua_physics_manual.cpp
  extensions/scripting/lua-bindings/manual/physics3d/axlua_physics3d_manual.cpp
  extensions/scripting/lua-bindings/manual/spine/axlua_spine_manual.cpp
  extensions/scripting/lua-bindings/manual/ui/axlua_ui_manual.cpp
  tests/lua-tests/Source/lua_test_bindings.cpp
Labels: Axmol-v3, refactor

#2768 Improve/Fix DrawNodeTest.cpp
  tests/cpp-tests/Source/DrawNodeTest/DrawNodeTest.cpp
Labels: enhancement

#2762 Handling screen orientation change for all platforms
  axmol/platform/Application.h
  axmol/platform/ApplicationBase.cpp
  axmol/platform/ApplicationBase.h
  axmol/platform/RenderView.cpp
  axmol/platform/RenderView.h
  axmol/platform/SAXParser.h
  axmol/platform/android/Application-android.cpp
  axmol/platform/android/Application-android.h
  axmol/platform/android/RenderViewImpl-android.cpp
  axmol/platform/android/javaactivity-android.cpp
  axmol/platform/apple/Device-apple.h
  axmol/platform/apple/Device-apple.mm
  axmol/platform/apple/FileUtils-apple.h
  axmol/platform/desktop/Device-desktop.cpp
  axmol/platform/desktop/RenderViewImpl.cpp
  axmol/platform/desktop/RenderViewImpl.h
  axmol/platform/ios/Application-ios.h
  axmol/platform/ios/Application-ios.mm
  axmol/platform/ios/DirectorCaller-ios.h
  axmol/platform/ios/DirectorCaller-ios.mm
  axmol/platform/ios/EARenderView-ios.h
  axmol/platform/ios/EARenderView-ios.mm
  axmol/platform/ios/ES3Renderer-ios.h
  axmol/platform/ios/ES3Renderer-ios.m
  axmol/platform/ios/ESRenderer-ios.h
  axmol/platform/ios/RenderViewImpl-ios.mm
  axmol/platform/linux/Application-linux.cpp
  axmol/platform/linux/FileUtils-linux.h
  axmol/platform/linux/GL-linux.h
  axmol/platform/linux/StdC-linux.h
  axmol/platform/mac/Application-mac.mm
  axmol/platform/mac/GL-mac.h
  axmol/platform/mac/StdC-mac.h
  axmol/platform/wasm/Application-wasm.h
  axmol/platform/wasm/devtools-wasm.h
  axmol/platform/win32/StdC-win32.cpp
  axmol/platform/winrt/RenderViewImpl-winrt.cpp
  templates/common/proj.ios_mac/ios/RootViewController.mm
  tests/cpp-tests/Source/AppDelegate.cpp
  tests/cpp-tests/Source/AppDelegate.h
  tests/cpp-tests/proj.android/app/build.gradle
Labels: enhancement

#2778 fix(wasm): improve frame timing and runtime compatibility
  1k/build.profiles
  axmol/platform/Device.h
  axmol/platform/android/Device-android.cpp
  axmol/platform/desktop/Device-desktop.cpp
  axmol/platform/ios/Device-ios.mm
  axmol/platform/wasm/Application-wasm.cpp
  cmake/Modules/AXBuildHelpers.cmake
  cmake/Modules/AXConfigDefine.cmake
  tests/cpp-tests/Source/ClippingNodeTest/ClippingNodeTest.cpp
Labels: enhancement, compatibility

#2772 Initial implementation adding support for audio effects and filters using OpenAL
  core/audio/AudioCache.h
  core/audio/AudioEffects.h
  core/audio/AudioEffectsExtension.cpp
  core/audio/AudioEffectsExtension.h
  core/audio/AudioEngine.cpp
  core/audio/AudioEngine.h
  core/audio/AudioEngineImpl.cpp
  core/audio/AudioEngineImpl.h
  core/audio/AudioPlayer.cpp
  core/audio/AudioPlayer.h
  core/audio/CMakeLists.txt
  core/audio/oal_port.h
  tests/cpp-tests/Source/AudioEngineTest/AudioEngineTest.cpp
  tests/cpp-tests/Source/AudioEngineTest/AudioEngineTest.h
Labels: enhancement

#2779 Fix reverb properties values
  core/audio/AudioEffects.h
  core/audio/AudioEngine.cpp
  core/audio/AudioEngine.h
  core/audio/AudioEngineImpl.cpp
  core/audio/AudioEngineImpl.h
  core/audio/AudioPlayer.cpp
  core/audio/AudioPlayer.h
Labels: enhancement

#2788 Fix effekseer & imgui render resource state
  axmol/base/Types.h
  axmol/platform/desktop/RenderViewImpl.cpp
  axmol/platform/linux/Application-linux.cpp
  axmol/platform/wasm/Application-wasm.cpp
  axmol/platform/win32/Application-win32.cpp
  axmol/platform/winrt/Application-winrt.cpp
  axmol/rhi/RHITypes.h
  axmol/rhi/opengl/CommandBufferGL.cpp
  axmol/rhi/opengl/DriverGL.cpp
  axmol/rhi/opengl/DriverGL.h
  axmol/rhi/opengl/OpenGLState.cpp
  axmol/rhi/opengl/OpenGLState.h
  extensions/Effekseer/EffekseerRendererGL/EffekseerRenderer/EffekseerRendererGL.Renderer.cpp
  extensions/Effekseer/EffekseerRendererLLGI/Common.cpp
  extensions/ImGui/src/ImGui/backends/imgui_impl_axmol.cpp
  extensions/ImGui/src/ImGui/backends/imgui_impl_axmol.h
  extensions/ImGui/src/ImGui/backends/imgui_impl_glfw.cpp
  extensions/scripting/lua-bindings/auto/axlua_base_auto.cpp
Labels: bug

#2790 Rename initGfxContexAttrs => initContextAttrs
  1k/platforms.cmake
  axmol/base/Director.h
  axmol/base/Types.h
  axmol/platform/ApplicationBase.cpp
  axmol/platform/ApplicationBase.h
  axmol/platform/RenderView.cpp
  axmol/platform/RenderView.h
  axmol/platform/android/javaactivity-android.cpp
  axmol/platform/android/libaxmol/build.gradle
  axmol/platform/desktop/RenderViewImpl.cpp
  axmol/platform/ios/AxmolAppController.mm
  axmol/platform/ios/RenderViewImpl-ios.mm
  axmol/platform/linux/Application-linux.cpp
  axmol/platform/mac/Application-mac.mm
  axmol/platform/wasm/Application-wasm.cpp
  axmol/platform/win32/Application-win32.cpp
  axmol/platform/winrt/xaml/AxmolRenderer.cpp
  axmol/rhi/DriverBase.cpp
  axmol/rhi/DriverBase.h
  axmol/rhi/RHITypes.h
  axmol/rhi/d3d/CommandBufferD3D.cpp
  axmol/rhi/d3d/DriverD3D.cpp
  axmol/rhi/metal/CommandBufferMTL.mm
  cmake/Modules/AXConfigDefine.cmake
  extensions/scripting/lua-bindings/auto/axlua_base_auto.cpp
  extensions/scripting/lua-bindings/auto/axlua_rhi_auto.cpp
  templates/cpp/Source/AppDelegate.cpp
  templates/cpp/Source/AppDelegate.h
  templates/lua/Source/AppDelegate.cpp
  templates/lua/Source/AppDelegate.h
  tests/cpp-tests/Source/AppDelegate.cpp
  tests/cpp-tests/Source/AppDelegate.h
  tests/cpp-tests/proj.android/settings.gradle
  tests/fairygui-tests/Source/AppDelegate.cpp
  tests/fairygui-tests/Source/AppDelegate.h
  tests/live2d-tests/Source/AppDelegate.cpp
  tests/live2d-tests/Source/AppDelegate.h
  tests/lua-tests/Source/AppDelegate.cpp
  tests/lua-tests/Source/AppDelegate.h
  tests/unit-tests/Source/AppDelegate.cpp
  tests/unit-tests/Source/AppDelegate.h
Labels: breaking changes

#2802 Fix for crash when director is reset during scene transition
  core/base/Director.cpp
Labels: bug, enhancement

#2803 Update gradle: 9.0.0 => 9.1.0
  1k/1kiss.ps1
  1k/build.profiles
  1k/fetch.ps1
  INFRA.md
  templates/common/proj.android/gradle/wrapper/gradle-wrapper.properties
  templates/common/proj.android/gradlew
  templates/common/proj.android/gradlew.bat
  tests/cpp-tests/proj.android/gradle/wrapper/gradle-wrapper.properties
  tests/cpp-tests/proj.android/gradlew
  tests/cpp-tests/proj.android/gradlew.bat
  tests/fairygui-tests/proj.android/gradle/wrapper/gradle-wrapper.properties
  tests/fairygui-tests/proj.android/gradlew
  tests/fairygui-tests/proj.android/gradlew.bat
  tests/live2d-tests/proj.android/gradle/wrapper/gradle-wrapper.properties
  tests/live2d-tests/proj.android/gradlew
  tests/live2d-tests/proj.android/gradlew.bat
  tests/lua-tests/proj.android/gradle/wrapper/gradle-wrapper.properties
  tests/lua-tests/proj.android/gradlew
  tests/lua-tests/proj.android/gradlew.bat
  tests/unit-tests/proj.android/gradle/wrapper/gradle-wrapper.properties
  tests/unit-tests/proj.android/gradlew
  tests/unit-tests/proj.android/gradlew.bat
Labels: enhancement

#2805 feat(http): add setDataCallback for streaming data support
  core/network/HttpClient.cpp
  core/network/HttpClient.h
  core/network/HttpRequest.h
  core/network/HttpResponse.h
Labels: enhancement
